import Image from 'next/image'
import Head from 'next/head';

import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import TopCards from '@/components/TopCards';
import RecentOrders from '@/components/RecentOrders';
import BarCharts from '@/components/BarCharts';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
        <link rel='icon' href='/Demo2/favicon.ico' /> 
      </Head>
      <main className='bg-gray-100 min-h-screen'>
      <Header />
      <TopCards />
      <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
        <RecentOrders/>
        <BarCharts/>
      </div>
      </main>

    </> 
  );
}
